# Generated by Django 6.0.5 on 2026-07-10 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='muted_by',
            field=models.ManyToManyField(blank=True, related_name='muted_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
