# Generated by Django 6.0.5 on 2026-07-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_message_is_system_thread_group_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers_only',
            field=models.BooleanField(default=False),
        ),
    ]
