# Generated by Django 6.0.5 on 2026-07-21 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_storyview_likes_story_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyview',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='network.story'),
        ),
    ]
