# Generated by Django 6.0.5 on 2026-07-08 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='network.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('message', 'Message'), ('comment', 'Comment'), ('like', 'Like'), ('dislike', 'Dislike')], max_length=20),
        ),
    ]
