# Generated by Django 6.0.5 on 2026-07-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_storyview_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
