# Generated by Django 6.0.5 on 2026-07-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_comment_parent_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('message', 'Message'), ('comment', 'Comment'), ('like', 'Like'), ('dislike', 'Dislike'), ('tag', 'Tag')], max_length=20),
        ),
    ]
