# Generated by Django 6.0.5 on 2026-07-22 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_story_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='custom_stories_allowed', to=settings.AUTH_USER_MODEL),
        ),
    ]
