# Generated by Django 6.0.5 on 2026-07-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('unfollow', 'Unfollow'), ('comment', 'Comment'), ('like', 'Like'), ('dislike', 'Dislike'), ('tag', 'Tag')], max_length=20),
        ),
    ]
